# Generated by Django 5.1 on 2024-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='logotip/')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='logotip/')),
                ('title', models.CharField(max_length=155, verbose_name='Ник')),
                ('money', models.ImageField(max_length=155, upload_to='', verbose_name='Деньги')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotip', models.ImageField(upload_to='logotip/')),
                ('title_1', models.CharField(max_length=155, verbose_name='Заголовок 1')),
                ('title_2', models.CharField(max_length=155, verbose_name='Заголовок 2')),
            ],
        ),
    ]
